### ISSUE TITLE
Warning Undefined variable $unreadPostsCounter / Undefined array key "fid"

### ISSUE THREAD

**Issue by schauan** [lukasamd/MyBB-View_Unread_posts#34]
After Changing php-version from 7.4.30 to 8.2. I get this warnings:

Type: 2
File: inc/plugins/unreadPosts.php(318) : eval()'d code (Line no. 3) Message Undefined variable $unreadPostsCounter Back Trace: #0 /mnt/web016/e3/82/56775182/htdocs/cef/inc/class_error.php(239): errorHandler->email_error(2, '...', '...', 3)
#1 /mnt/web016/e3/82/56775182/htdocs/cef/inc/class_error.php(153): errorHandler->error(2, '...', '...', 3)
#2 /mnt/web016/e3/82/56775182/htdocs/cef/inc/plugins/unreadPosts.php(318) : eval()'d code(3): errorHandler->error_callback(2, '...', '...', 3)
#3 /mnt/web016/e3/82/56775182/htdocs/cef/inc/plugins/unreadPosts.php(318): eval()
#4 /mnt/web016/e3/82/56775182/htdocs/cef/inc/class_plugins.php(136): unreadPosts::xmlhttpGetUnreads('')
#5 /mnt/web016/e3/82/56775182/htdocs/cef/xmlhttp.php(205): pluginSystem->run_hooks(Array)

Type: 2
File: inc/plugins/unreadPosts.php (Line no. 275) Message Undefined array key "fid"
Back Trace: #0 /mnt/web016/e3/82/56775182/htdocs/cef/inc/class_error.php(239): errorHandler->email_error(2, '...', '...', 275)
#1 /mnt/web016/e3/82/56775182/htdocs/cef/inc/class_error.php(153): errorHandler->error(2, '...', '...', 275)
#2 /mnt/web016/e3/82/56775182/htdocs/cef/inc/plugins/unreadPosts.php(275): errorHandler->error_callback(2, '...', '...', 275)
#3 /mnt/web016/e3/82/56775182/htdocs/cef/inc/class_plugins.php(136): unreadPosts::xmlhttpGetUnreads('')
#4 /mnt/web016/e3/82/56775182/htdocs/cef/xmlhttp.php(205): pluginSystem->run_hooks(Array)

I had changed line 484 with npp to 
"ipaddress" => $db->escape_binary($session->packedip),
see issue #33 
(see the file in the zip) 

In functions_indicators.php I have some changes for mybb 1.8.38, but the warnings comes with the original plugin file too.
(see the file in the zip) 
 
[unread.zip](https://github.com/user-attachments/files/16687884/unread.zip)

**Comment by schauan** [comment]
Hallo,

sorry. I tried it in a blank forum. There I get only one another warning:

Warning [2] Undefined array key "action" - Line: 183 - File: inc/plugins/unreadPosts.php PHP 8.2.22 (Linux)
File	Line	Function
/inc/class_error.php	153	errorHandler->error
/inc/plugins/unreadPosts.php	183	errorHandler->error_callback
/inc/class_plugins.php	136	unreadPosts::actionNewpost
/global.php	1276	pluginSystem->run_hooks
/showthread.php	28	require_once
